---
title: "NTU_新加坡南洋理工大学"
format: html
toc: true
editor: visual
---

## School Info 学校介绍

**QS综合排名:** 15

**QS学科排名：** Data Science 数据科学：5 ; Statistics 统计：28

## Master of Science in Data Science (MSDS) 理学硕士：数据科学

### Program Website [项目官网](https://www.ntu.edu.sg/education/graduate-programme/master-of-science-in-data-science-(msds))

>Data science is a data-driven approach to problem solving and scientific exploration that involves the process of collecting, managing, analyzing, explaining, and visualizing data and analysis results. It is inherently interdisciplinary in nature. The aim of the Master of Science in Data Science (MSDS) programme is to provide graduate students with robust training in the field of Data Science.  The program is led and mainly run by the College of Computing and Data Science (CCDS). Faculty members from several other schools also actively contributes to this programme to support interdisciplinary flavour of data science.数据科学是一种以数据为导向的解决问题和科学探索方法，涉及数据和分析结果的收集、管理、分析、解释和可视化过程。它本质上是一门跨学科的学科。数据科学理学硕士（MSDS）课程旨在为研究生提供数据科学领域的有力培训。 该项目主要由计算机与数据科学学院（CCDS）领导和运作。其他几个学院的教师也积极为该计划做出贡献，以支持数据科学的跨学科研究。

### [Application Material](https://www.ntu.edu.sg/images/librariesprovider118/programmes/pg/admissionrequirements_apr2025.png?sfvrsn=7b4c1e99_4)

- Passport 护照

- Certification Letter for Medium of Instruction from Bachler Degree School 学位学校的教学语言证明信


- Official Transcript 官方成绩单

- CV 简历

- GPA 成绩

- Pursue Reason 文书

- Optional: GRE and Referrence letter 

### 

