---
title: "NTU 新加坡南洋理工大学"
format: html
toc: true
editor: visual
---

## School Info 学校介绍

**QS综合排名:** 15

**QS学科排名：** Data Science 数据科学：5 ; Statistics 统计：28

## Master of Science in Data Science (MSDS) 理学硕士：数据科学

### Program Website [项目官网](https://www.ntu.edu.sg/education/graduate-programme/master-of-science-in-data-science-(msds))

> Data science is a data-driven approach to problem solving and scientific exploration that involves the process of collecting, managing, analyzing, explaining, and visualizing data and analysis results. It is inherently interdisciplinary in nature. The aim of the Master of Science in Data Science (MSDS) programme is to provide graduate students with robust training in the field of Data Science. The program is led and mainly run by the College of Computing and Data Science (CCDS). Faculty members from several other schools also actively contributes to this programme to support interdisciplinary flavour of data science.数据科学是一种以数据为导向的解决问题和科学探索方法，涉及数据和分析结果的收集、管理、分析、解释和可视化过程。它本质上是一门跨学科的学科。数据科学理学硕士（MSDS）课程旨在为研究生提供数据科学领域的有力培训。 该项目主要由计算机与数据科学学院（CCDS）领导和运作。其他几个学院的教师也积极为该计划做出贡献，以支持数据科学的跨学科研究。

### [Application Material申请材料](https://www.ntu.edu.sg/images/librariesprovider118/programmes/pg/admissionrequirements_apr2025.png?sfvrsn=7b4c1e99_4)

-   Passport 护照

-   Certification Letter for Medium of Instruction from Bachler Degree School 学位学校的教学语言证明信

-   Official Transcript 官方成绩单

-   CV 简历

-   GPA 成绩

-   Pursue Reason 文书

-   Optional: GRE and Referrence letter

### Cost费用

> Tuition Fees: S\$63,220

> Deposit Fees: S\$5,000 – This amount will be deducted from the first billing.(Payable upon acceptance of offer of admission)

> Payment Schedule: Full-time students will be billed in 2 semesters while part-time students will be billed in 4 semesters.

> 学费 63,220 新加坡元

> 押金费用： 5,000 新元 - 此金额将从第一份账单中扣除。 (接受录取通知书时支付）

> 付款时间表： 全日制学生的学费将分 2 个学期支付，非全日制学生的学费将分 4 个学期支付。

Additional Cost for international students 其他国际学生[费用](%22https://www.ntu.edu.sg/computing/admissions/graduate-programmes/master-of-science-programmes/international-students%22): includes room and board, personal expences, travel, etc.包括住宿，吃饭，个人消费，通勤等

### [Curriculum 课程设置](https://www.ntu.edu.sg/docs/librariesprovider118/pg/coursecontent_msds_15aug24-.pdf?sfvrsn=9d5a28bf_3)

> 全日制 1-2/5 年

> 非全日制 2-4 年

### [Unique Features of this program 项目独特之处](https://www.ntu.edu.sg/education/graduate-programme/master-of-science-in-data-science-(msds)#unique)

> Tight integration of relevant theories and principles from social sciences with computing-driven data science. Given that data is generated by humans or machines, it is paramount to consider social context for any data science problem. Consequently, the core courses focus not only on computing-driven data science courses but also courses and projects that steer students to take a realistic look at a data science problem by considering various social, economics, and behavioural issues. A wide range of elective courses to tackle various data types one may encounter in different application domains along with deeper insights to psychology and economic theories are provided to broaden the knowledge.将社会科学的相关理论和原则与计算驱动的数据科学紧密结合。鉴于数据是由人类或机器生成的，因此考虑任何数据科学问题的社会背景至关重要。因此，核心课程不仅侧重于计算驱动的数据科学课程，还包括引导学生通过考虑各种社会、经济和行为问题，以现实的眼光看待数据科学问题的课程和项目。为了拓宽知识面，还提供了一系列选修课程，以解决在不同应用领域可能遇到的各种数据类型问题，并深入探讨心理学和经济学理论。

> Comprehensive coverage of the data science ecosystem. In MSDS program, we do not just simply teach analytics. Data analytics techniques are ineffective if your input data is dirty, messy, and not ready for analysis! Our program ensures every student goes through the entire data science ecosystem – from data preparation to data visualization, giving them a comprehensive depth and breadth of data science.全面覆盖数据科学生态系统。在MSDS课程中，我们不仅仅教授分析技术。如果输入的数据肮脏、杂乱，无法进行分析，那么数据分析技术就会失效！从数据准备到数据可视化，我们的课程确保每位学生都能了解整个数据科学生态系统，从而全面深入地学习数据科学。

> The Capstone Project gives students hands-on opportunities to realize the data science ecosystem for domain-specific applications in industrial settings or academia. The former enables a student to address industry-specific data science problem whereas the latter allows a student opportunity to address such problem for non-industrial end users.毕业设计项目为学生提供了实践机会，使他们能够在工业环境或学术界的特定领域应用中实现数据科学生态系统。前者让学生能够解决特定行业的数据科学问题，而后者则让学生有机会解决非特定行业的数据科学问题。

> Inter-disciplinary nature of MSDS is supported by courses taught by faculty members from different schools. In particular, the core course entitled “Data Science Thinking” will be jointly taught by faculty members from the School of Social Sciences (SSS) and CCDS. Several electives are also taught by faculty members of SSS and the School of Physical and Mathematical Sciences (SPMS). Furthermore, students may take an application domain-specific elective that may be offered by any school (e.g., NBS, SBS, ASE, MAE, EEE, SPMS, SSS, LKC) in NTU (excluding CCDS). Lastly, a capstone project in the MSDS program can be a collaboration between domain-specific industry participants, faculty members from various schools and CCDS.由不同学院的教师讲授的课程支持了 MSDS 的跨学科性质。其中，题为 “数据科学思维 ”的核心课程将由社会科学学院（SSS）和计算机科学与数据科学学院（CCDS）的教师联合讲授。多门选修课也由社会科学学院和物理与数学科学学院（SPMS）的教师讲授。此外，学生还可选修一门应用领域选修课，该选修课可由南洋理工大学的任何一个学院（如国家统计局、国家统计局、美国空间工程师学会、美国工程硕士学会、欧洲电子工程师学会、南洋理工大学物理与数学科学学院、南洋理工大学社会科学学院、南洋理工大学荔枝角分校）提供（不包括南洋理工大学社会科学与数学科学学院）。最后，MSDS 课程的顶点项目可由特定领域的行业参与者、不同学院的教师和 CCDS 合作完成。
